
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: yandex-cloud-controller-manager
  name: yandex-cloud
stringData:
  service-account-json: |
    {{ .Values.yccm.cloud_secret | toJson | indent 4 }}
  folder-id: {{ .Values.yccm.folder_id }}
  vpc-id: {{ .Values.yccm.vpc_id }}
  route_table_id: {{ .Values.yccm.route_table_id }}
