---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yandex-csi-controller.name" . }}
type: Opaque
stringData:
  serviceAccountJSON: |
    {{ .Values.ycsi.cloud_secret | toJson | indent 4 }}
  folderID: {{ .Values.ycsi.folder_id }}