---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: yc-network-hdd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: yandex.csi.flant.com
parameters:
  typeID: network-hdd
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: yc-network-ssd
provisioner: yandex.csi.flant.com
parameters:
  typeID: network-ssd
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: yc-network-ssd-nonreplicated
provisioner: yandex.csi.flant.com
parameters:
  typeID: network-ssd-nonreplicated
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete